In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [8]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,44.1708,8.717,30016
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,35.7699,8.687,22672
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,23.1115,8.572,13729
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.8532,8.567,17253
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.9162,8.557,9851

In [11]:
df = pd.DataFrame()

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [20]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,44.1708,8.717,30016
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,35.7699,8.687,22672
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,23.1115,8.572,13729
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.8532,8.567,17253
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,18.9162,8.557,9851
...,...,...,...,...,...,...,...
17115,209112,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,2016-03-23,17.0116,5.992,18842
17116,59861,Larry Crowne,When he suddenly finds himself without his lon...,2011-06-30,3.4886,5.992,1407
17117,19384,Dark Angel,Jack Caine is a Houston vice cop who's forgott...,1990-01-26,2.6543,6.000,353
17118,17336,Fighting,Small-town boy Shawn MacArthur has come to New...,2009-04-24,2.3579,5.992,753
17119,11678,Vertical Limit,"Trapped near the summit of K2, the world's sec...",2000-12-08,3.2140,5.992,1120

In [21]:
df.shape

(17120, 7)

In [22]:
df.to_csv('movies.csv')